from typing import List, Dict, TypedDict, Annotated
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: Original natural-language question from the user.
        messages: Conversation history between the user and the assistant.
        intent: Whether the user's question is "auto_parts" or "off_topic".
        resolved_question: Standalone auto parts question rewritten from conversation context. Used to recommend instead of raw question.
        sql_query: SQL query generated by the LLM for retrieving candidate products.
        error_message: Error message if the generated SQL query is invalid or fails to execute.
        query_results: Product rows returned from the SQLite database.
        generation: Final natural-language response shown to the user.
        retry_count: Number of SQL generation attempts. Used to prevent infinite retry loops.
    """

    question: str
    messages: Annotated[list[AnyMessage], add_messages]

    intent: str
    resolved_question: str

    sql_query: str
    error_message: str
    query_results: List[Dict]
    generation: str
    retry_count: int
