from typing import List, Dict, TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: Original natural-language question from the user.
        sql_query: SQL query generated by the LLM for retrieving candidate products.
        error_message: Error message if the generated SQL query is invalid or fails to execute.
        query_results: Product rows returned from the SQLite database.
        generation: Final natural-language response shown to the user.
        retry_count: Number of SQL generation attempts. Used to prevent infinite retry loops.
    """

    question: str
    sql_query: str
    error_message: str
    query_results: List[Dict]
    generation: str
    retry_count: int
